#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate an Anki CSV batch from source-backed pending candidates."""

from __future__ import annotations

import argparse
import csv
import re
import sqlite3
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DB_PATH = ROOT / ".agent" / "state" / "progress.sqlite"
BATCH_DIR = ROOT / "outputs" / "anki" / "law_study_batches"
BLOCKED_TEXT = ("자료 부족—보류", "source 없음")


def safe_slug(value: str) -> str:
    return re.sub(r"[^0-9A-Za-z가-힣_.-]+", "_", value).strip("_") or "all"


def fetch_candidates(conn: sqlite3.Connection, category: str | None, limit: int) -> list[sqlite3.Row]:
    params: list[object] = []
    where = [
        "status IN ('pending', 'updated')",
        "COALESCE(source_file, '') <> ''",
        "COALESCE(source_location, '') <> ''",
        "COALESCE(front, '') <> ''",
        "COALESCE(back, '') <> ''",
    ]
    if category:
        where.append("category_id = ?")
        params.append(category)
    sql = f"""
        SELECT *
        FROM anki_candidates
        WHERE {" AND ".join(where)}
        ORDER BY export_priority DESC, updated_at DESC, card_id ASC
        LIMIT ?
    """
    params.append(limit)
    rows = []
    for row in conn.execute(sql, params):
        joined = "\n".join(str(row[key] or "") for key in ("front", "back", "extra"))
        if any(blocked in joined for blocked in BLOCKED_TEXT):
            continue
        rows.append(row)
    return rows


def batch_id(category: str | None) -> str:
    return f"anki_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{safe_slug(category or 'all')}"


def write_csv(path: Path, rows: list[sqlite3.Row]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        f.write("#separator:Comma\n")
        f.write("#html:true\n")
        f.write("#notetype:LawBasic\n")
        f.write("#deck column:2\n")
        f.write("#tags column:7\n")
        f.write("#columns:note_key,deck,front,back,extra,source,tags\n")
        writer = csv.writer(f)
        for row in rows:
            source = f"{row['source_file']} > {row['source_location']}"
            writer.writerow(
                [
                    row["note_key"],
                    row["deck"],
                    row["front"],
                    row["back"],
                    row["extra"] or "",
                    source,
                    row["tags"] or "",
                ]
            )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate source-backed Anki batch CSV.")
    parser.add_argument("--category", help="category_id filter")
    parser.add_argument("--limit", type=int, default=50)
    parser.add_argument("--db", default=str(DB_PATH))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    conn = sqlite3.connect(args.db)
    conn.row_factory = sqlite3.Row
    try:
        rows = fetch_candidates(conn, args.category, args.limit)
        if not rows:
            print("No exportable candidates.")
            return 0

        bid = batch_id(args.category)
        category_id = args.category or rows[0]["category_id"] or "mixed"
        subject_group = None
        deck_name = rows[0]["deck"]
        out_path = BATCH_DIR / f"{bid}.csv"

        if args.dry_run:
            print(f"Dry run: {len(rows)} cards would be written to {out_path}")
            return 0

        write_csv(out_path, rows)
        now = datetime.now().isoformat(timespec="seconds")
        new_count = sum(1 for r in rows if r["status"] == "pending")
        update_count = sum(1 for r in rows if r["status"] == "updated")
        repeated_count = sum(
            1
            for r in rows
            if "반복오답" in (r["extra"] or "") or "repeated_error" in (r["tags"] or "")
        )
        conn.execute(
            """
            INSERT INTO anki_batches (
              batch_id, category_id, subject_group, deck_name, file_path,
              card_count, new_card_count, update_card_count,
              repeated_error_card_count, generated_at, status, notes
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'generated', ?)
            """,
            (
                bid,
                category_id,
                subject_group,
                deck_name,
                str(out_path.relative_to(ROOT)),
                len(rows),
                new_count,
                update_count,
                repeated_count,
                now,
                "generated by .agent/scripts/generate_anki_batch.py",
            ),
        )
        conn.executemany(
            "UPDATE anki_candidates SET status = 'batched', batch_id = ?, updated_at = ? WHERE card_id = ?",
            [(bid, now, r["card_id"]) for r in rows],
        )
        conn.commit()
        print(f"Batch: {bid}")
        print(f"Cards: {len(rows)}")
        print(f"File: {out_path}")
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
